name: homeassistant

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    # Persistent configuration
    environment:
      TZ: 'America/New_York'
    restart: unless-stopped
    volumes:
      - volume:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
volumes:
  volume:
