services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    volumes:
      - prometheus_volume:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


  prometheus-node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
    networks:
      - network
    deploy:
      mode: global


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_volume:/var/lib/grafana
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]


networks:
  network:
    driver: overlay
    attachable: true

volumes:
  prometheus_volume:
  grafana_volume:
