# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
name: pihole

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    # Use host networking so Pi-hole can see real client IPs
    # and avoid Docker Swarm/overlay NAT rewriting source addresses
    network_mode: host
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/New_York'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: '${PIHOLE_PASSWORD}'
      # Pi-hole DNS listening mode
      FTLCONF_dns_listeningMode: 'all'
      # Web admin port, because host port 80 is already in use
      FTLCONF_webserver_port: '8080'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - volume:/etc/pihole

    restart: unless-stopped

volumes:
  volume:
