services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - volume:/var/lib/postgresql/data
    networks:
      - network
    environment:
      POSTGRES_DB: homelab
      POSTGRES_USER: kmasouri
      POSTGRES_PASSWORD: password
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  network:
    driver: overlay
    attachable: true

volumes:
  volume:
