global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    dns_sd_configs:
      - names:
          - "tasks.monitoring_prometheus-node-exporter"
        type: A
        port: 9100
